//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEngeneering.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class component
    {
        public int id { get; set; }
        public int id_material { get; set; }
        public string title { get; set; }
        public int id_technic { get; set; }
        public double volume { get; set; }
    
        public virtual technic_types technic_types { get; set; }
        public virtual material material { get; set; }
    }
}
